### ISSUE TITLE
Verify changes / deployment

### ISSUE THREAD

**Issue by jstabenow** [mesosphere/jenkins-marathon-plugin#16]
Hey @colin-msphere 

I use a small script to verify if my changes are successfully deployed by marathon. The benefit is a automatic rollback of my app, if something is wrong (e.g. exec error with the new Docker image).
Maybe that's also a good extension for your plugin.

Here my script:
```sh
# 1. push new app.json
deploymentId=$(curl --silent -X PUT -H "Accept: application/json" -H "Content-Type: application/json" marathon.mesos:8080/v2/apps/$1 --data @$1.json | jq '.deploymentId' | cut -f2 -d'"')
echo "Deployment: $deploymentId CREATED"

# 2. check open deployments
sleep $2
getActiveDeploymentIds=$(curl --silent -H "Accept: application/json" -H "Content-Type: application/json" marathon.mesos:8080/v2/deployments | jq '.[].id' | cut -f2 -d'"')
compareDeploymentIds=$(echo $getActiveDeploymentIds | grep "$deploymentId" | sort -nr)

# 3. cancel my deployment if it is still open
if [ "$deploymentId" = "$compareDeploymentIds" ]
then
  curl --silent -X DELETE -H "Accept: application/json" -H "Content-Type: application/json" marathon.mesos:8080/v2/deployments/$deploymentId
  echo "Deployment: $deploymentId FAILED"
  exit 1
else
  echo "Deployment: $deploymentId SUCCESS"
fi
```

Jenkins job "Shell" example:
```sh
docker build ...
docker push ...
echo '{
  "container": { 
    "type": "DOCKER",
    "docker": {
      "image": "repo/app:'$BUILD_NUMBER'",
      "network": "BRIDGE",
      "portMappings": [...]
    },
    "volumes": [...]
  }
}' > app.json
./deploy.sh app 360
```

If it's not interesting, you can close this "issue" ;-)

**Comment by ssk2** [comment]
Thanks for the issue @jstabenow - preferably we'd delegate this logic to Marathon itself and it's update strategy. Any reason you would prefer this over setting the minimumHealthCapacity for your Marathon application?

**Comment by jstabenow** [comment]
Hey @ssk2 
Thanks for your reply. 
Yes I'm working with minimumHealthCapacity and maximumOverCapacity but the problem is:

> [A failed Deployment](https://mesosphere.github.io/marathon/docs/deployments.html#a-failed-deployment)
> ...
> The deployment in this case would take forever. To heal the system, a new deployment must be applied to correct the problem with the current deployment.

My script checks (./deploy.sh app max-time-to-deploy) if my deployment-id is finished or not. If is not, this can be a problem and my script deletes the deployment-id and marathon starts the rollback. 

It's not perfect because I have to calculate the time for a full deployment per app. But it's better than a failed deployment over night and a morning with many failed Mesos tasks ;-)

Maybe it's not so critical to you because your other solutions are working with blue/green workflows and certainly a better health/rollback-logic... But it is a very easy way to check/verify the deployment.

**Comment by ssk2** [comment]
Hey @jstabenow - sorry for the delay. I spoke to the Marathon team about this and this should really be functionality built into the Marathon deployments API. Feature request is here: https://github.com/mesosphere/marathon/issues/3954.
