### ISSUE TITLE
mvn hpi:run fails to find com.mesosphere:marathon-client:jar:0.2.0

### ISSUE THREAD

**Issue by john-dohoney** [mesosphere/jenkins-marathon-plugin#21]
The Jenkins Plugin failed to build.  See below, the issue is a missing jar file, com.mesosphere:marathon-client:jar:0.2.0  How can I resolve this?

Environment:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"

Steps to re-create:
1. git clone https://github.com/mesosphere/jenkins-marathon-plugin.git
2. cd jenkins-marathon-plugin/
3. mvn hpi:run

Error Produced:
[INFO] Scanning for projects...
Downloading: http://repo.jenkins-ci.org/public/org/apache/maven/plugins/maven-idea-plugin/2.2/maven-idea-plugin-2.2.pom
Downloaded: http://repo.jenkins-ci.org/public/org/apache/maven/plugins/maven-idea-plugin/2.2/maven-idea-plugin-2.2.pom (14 KB at 20.4 KB/sec)
Downloading: http://repo.jenkins-ci.org/public/org/apache/maven/plugins/maven-plugins/11/maven-plugins-11.pom
Downloaded: http://repo.jenkins-ci.org/public/org/apache/maven/plugins/maven-plugins/11/maven-plugins-11.pom (11 KB at 28.9 KB/sec)
Downloading: http://repo.jenkins-ci.org/public/org/apache/maven/plugins/maven-idea-plugin/2.2/maven-idea-plugin-2.2.jar
Downloaded: http://repo.jenkins-ci.org/public/org/apache/maven/plugins/maven-idea-plugin/2.2/maven-idea-plugin-2.2.jar (50 KB at 80.3 KB/sec)
Downloading: http://repo.jenkins-ci.org/public/org/apache/maven/plugins/maven-eclipse-plugin/2.8/maven-eclipse-plugin-2.8.pom
Downloaded: http://repo.jenkins-ci.org/public/org/apache/maven/plugins/maven-eclipse-plugin/2.8/maven-eclipse-plugin-2.8.pom (12 KB at 43.4 KB/sec)
Downloading: http://repo.jenkins-ci.org/public/org/apache/maven/plugins/maven-plugins/17/maven-plugins-17.pom
Downloaded: http://repo.jenkins-ci.org/public/org/apache/maven/plugins/maven-plugins/17/maven-plugins-17.pom (13 KB at 47.0 KB/sec)
Downloading: http://repo.jenkins-ci.org/public/org/apache/maven/plugins/maven-eclipse-plugin/2.8/maven-eclipse-plugin-2.8.jar
Downloaded: http://repo.jenkins-ci.org/public/org/apache/maven/plugins/maven-eclipse-plugin/2.8/maven-eclipse-plugin-2.8.jar (202 KB at 208.5 KB/sec)
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Marathon Deployment 1.2.1
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> maven-hpi-plugin:1.115:run (default-cli) @ marathon >>>
[WARNING] The POM for com.mesosphere:marathon-client:jar:0.2.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.427s
[INFO] Finished at: Wed May 25 22:09:52 UTC 2016
[INFO] Final Memory: 18M/44M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project marathon: Could not resolve dependencies for project com.mesosphere.velocity:marathon:hpi:1.2.1: Failure to find com.mesosphere:marathon-client:jar:0.2.0 in http://repo.jenkins-ci.org/public/ was cached in the local repository, resolution will not be reattempted until the update interval of repo.jenkins-ci.org has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by ssk2** [comment]
Please build the Marathon client JAR on the same machine so that Maven can resolve this dependency: https://github.com/mesosphere/marathon-client

In the future, this will be in Maven central so you won't have to do this manually.

**Comment by colin-msphere** [comment]
You will need to locally compile [marathon-client](https://github.com/mesosphere/marathon-client/tree/v0.2.0) and install it.

```
$ git clone --branch v0.2.0 https://github.com/mesosphere/marathon-client.git
$ cd marathon-client && mvn install
```

And then build the plugin again. I hope this helps.

Getting both this plugin and the `marathon-client` into their respective upstream repositories is in progress, but no ETA to share at this time.
